name: APK Inspector
description: Inspect the APK and extract the version

inputs:
  package_name:
    description: The package name of the APK
    required: true
  force_update:
    description: Force update the version
    required: false
    default: 'false'
  blacklist_versions:
    description: A comma-separated list of blacklisted versions
    required: false
    default: ''
  apk_url:
    description: Direct URL to the APK to download (overrides package name)
    required: false
    default: ''
  override_version:
    description: Override the detected version
    required: false
    default: ''

outputs:
  skip:
    description: Whether to skip the APK inspection
    value: ${{ steps.get-version.outputs.skip }}
  version:
    description: The version of the APK
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.24'

    - name: Get APK information
      shell: bash
      run: ./scripts/get_info.sh ${{ inputs.package_name }} ${{ inputs.override_version }} ${{ inputs.apk_url }}

    - name: Check the APK version
      id: get-version
      shell: bash
      run: ./scripts/extract_version.sh ${{ inputs.package_name }} ${{ inputs.force_update }} ${{ inputs.blacklist_versions }}

    - name: Download APK
      if: steps.get-version.outputs.skip == 'false'
      shell: bash
      run: ./scripts/download.sh ${{ inputs.package_name }} ${{ inputs.apk_url }}
